import type { Task } from "./types"

export const dummyTasks: Task[] = [
  {
    id: "1",
    title: "Data Structures Assignment",
    description: "Complete binary tree traversal problems from Chapter 5",
    category: "Academic",
    priority: "High",
    deadline: "2026-02-20",
    completed: false,
    createdAt: "2026-02-15",
  },
  {
    id: "2",
    title: "Linear Algebra Midterm",
    description: "Study eigenvalues, eigenvectors, and matrix decomposition",
    category: "Exams",
    priority: "High",
    deadline: "2026-02-22",
    completed: false,
    createdAt: "2026-02-10",
  },
  {
    id: "3",
    title: "LeetCode Daily Challenge",
    description: "Solve 3 medium-level dynamic programming problems",
    category: "Coding",
    priority: "Medium",
    deadline: "2026-02-19",
    completed: false,
    createdAt: "2026-02-17",
  },
  {
    id: "4",
    title: "Read Clean Code Ch. 7",
    description: "Chapter on error handling and boundaries in Clean Code by Robert C. Martin",
    category: "Reading",
    priority: "Low",
    deadline: "2026-02-25",
    completed: false,
    createdAt: "2026-02-14",
  },
  {
    id: "5",
    title: "Morning Run Routine",
    description: "Complete 5K morning jog before classes start",
    category: "Personal",
    priority: "Medium",
    deadline: "2026-02-19",
    completed: false,
    createdAt: "2026-02-16",
  },
  {
    id: "6",
    title: "Physics Lab Report",
    description: "Write up findings from pendulum experiment",
    category: "Academic",
    priority: "High",
    deadline: "2026-02-21",
    completed: false,
    createdAt: "2026-02-13",
  },
  {
    id: "7",
    title: "Build React Portfolio",
    description: "Deploy personal portfolio website using Next.js and Tailwind",
    category: "Coding",
    priority: "Medium",
    deadline: "2026-02-28",
    completed: false,
    createdAt: "2026-02-12",
  },
  {
    id: "8",
    title: "Database Systems Homework",
    description: "SQL joins and normalization exercises from textbook",
    category: "Academic",
    priority: "Medium",
    deadline: "2026-02-23",
    completed: false,
    createdAt: "2026-02-15",
  },
  {
    id: "9",
    title: "Completed: Calculus Quiz",
    description: "Integration techniques quiz completed",
    category: "Completed",
    priority: "High",
    deadline: "2026-02-14",
    completed: true,
    createdAt: "2026-02-10",
  },
  {
    id: "10",
    title: "Completed: Read Atomic Habits",
    description: "Finished reading Atomic Habits by James Clear",
    category: "Completed",
    priority: "Low",
    deadline: "2026-02-13",
    completed: true,
    createdAt: "2026-02-05",
  },
  {
    id: "11",
    title: "Chemistry Final Prep",
    description: "Review organic chemistry reaction mechanisms",
    category: "Exams",
    priority: "High",
    deadline: "2026-03-01",
    completed: false,
    createdAt: "2026-02-16",
  },
  {
    id: "12",
    title: "Read Design Patterns Book",
    description: "Gang of Four patterns: Factory, Observer, Strategy",
    category: "Reading",
    priority: "Medium",
    deadline: "2026-03-05",
    completed: false,
    createdAt: "2026-02-17",
  },
]
